### ISSUE TITLE
New links for PG Mods

### ISSUE THREAD

**Issue by once13one** [MuxaJlbl4/Awesome-PlayStation-Vita#15]
Hi! Thanks for awesome list and for adding links to our mods.
But, we have a some new changes on our sites. 
Please update the links if it's not hard.

PG Book: https://pgtmp.gitbook.io/pgbook/ – Guides for PS Vita on russian
PG Mods: https://pgtmp.gitbook.io/pgmods/ – Main page for our projects.
PG Mods Rus: https://pgtmp.gitbook.io/pgmods_rus/ – Main page for our projects on russian.

GTA Revisited Trilogy
GTA III 10thAE Mod: https://pgtmp.gitbook.io/pgmods/grand-theft-auto/revisited-trilogy/gta-iii
GTA VC 10thAE Mod: https://pgtmp.gitbook.io/pgmods/grand-theft-auto/revisited-trilogy/gta-vice-city
GTA SA PCAE Mod: https://pgtmp.gitbook.io/pgmods/grand-theft-auto/revisited-trilogy/gta-san-andreas

Max Payne PCAE Mod: https://pgtmp.gitbook.io/pgmods/other-games/max-payne
Minecraft: Enhanced (Release: Summer '23): https://pgtmp.gitbook.io/pgmods/other-games/minecraft-enhanced

Have a nice day ;)

**Comment by MuxaJlbl4** [comment]
Thanks for your cool mods and features! Links updated)
