### ISSUE TITLE
cwcheat vs tempar

### ISSUE THREAD

**Issue by Starmann** [MuxaJlbl4/Awesome-PlayStation-Vita#6]
You might wanna recommend TempAR. over CWCheat. TempAR is basically better in every way.

**Comment by MuxaJlbl4** [comment]
Thanks!) [Added some links to TempAR](https://github.com/MuxaJlbl4/Awesome-PlayStation-Vita/commit/9dccf169152330a214bfb4c3d58834f804083688)
