### ISSUE TITLE
https://pgteam.gitbook.io/pgbook site unavailable (404)

### ISSUE THREAD

**Issue by DvaMishkiLapa** [MuxaJlbl4/Awesome-PlayStation-Vita#7]
https://pgteam.gitbook.io/pgbook site unavailable. I don't know what happened to him.
Accordingly, the following links do not work:
- [GTA III 10th Anniversary Edition](https://pgteam.gitbook.io/pgbook/10thae) - 10th Anniversary Edition extensions for [re3](https://dl.coolatoms.org/vitadb/GTA3.vpk)[-vita](https://dl.coolatoms.org/vitadb/gta3.zip)
- [GTA: VC 10th Anniversary Edition](https://pgteam.gitbook.io/pgbook/vc10thae) - 10th Anniversary Edition extensions for [re3-miami](https://dl.coolatoms.org/vitadb/GTAVC.vpk)[-vita](https://dl.coolatoms.org/vitadb/vcdata.zip)
- [GTA: SA 10th Anniversary Edition](https://pgteam.gitbook.io/pgbook/sapcae) - 10th Anniversary Edition extensions for [GTA:SA](https://dl.coolatoms.org/vitadb/GTASA.vpk)[-vita](https://dl.coolatoms.org/vitadb/gtasa.zip)
- [Max Payne PC Anniversary Edition](https://pgteam.gitbook.io/pgbook/pcae) - PC version features for [max_vita](https://github.com/fgsfdsfgs/max_vita)
- [PGBook](https://pgteam.gitbook.io/pgbook) - PortableGaming guides and articles

I found a similar site, but I'm not sure if this is it. It does not contain the above articles.
https://pgtmp.gitbook.io/pgbook/

**Comment by DvaMishkiLapa** [comment]
Perhaps it will be something like this:
- [GTA III 10th Anniversary Edition](https://pgtmp.gitbook.io/pgbook/grand-theft-auto/revisited-trilogy/gta-iii) - 10th Anniversary Edition extensions for [re3](https://dl.coolatoms.org/vitadb/GTA3.vpk)[-vita](https://dl.coolatoms.org/vitadb/gta3.zip)
- [GTA: VC 10th Anniversary Edition](https://pgtmp.gitbook.io/pgbook/grand-theft-auto/revisited-trilogy/gta-vice-city) - 10th Anniversary Edition extensions for [re3-miami](https://dl.coolatoms.org/vitadb/GTAVC.vpk)[-vita](https://dl.coolatoms.org/vitadb/vcdata.zip)
- [GTA: SA 10th Anniversary Edition](https://pgtmp.gitbook.io/pgbook/grand-theft-auto/revisited-trilogy/gta-san-andreas) - 10th Anniversary Edition extensions for [GTA:SA](https://dl.coolatoms.org/vitadb/GTASA.vpk)[-vita](https://dl.coolatoms.org/vitadb/gtasa.zip)
- [Max Payne PC Anniversary Edition](https://pgtmp.gitbook.io/pgbook/other/max-payne) - PC version features for [max_vita](https://github.com/fgsfdsfgs/max_vita)
- [PGBook](https://pgtmp.gitbook.io/pgbook/) - PortableGaming guides and articles

I changed the links to the ones I suggested.

**Comment by MuxaJlbl4** [comment]
Thanks!) Links updated
